# Generated by Django 5.1.15 on 2026-02-16 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QnAAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='respuesta')),
                ('is_accepted', models.BooleanField(default=False, verbose_name='aceptada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
            ],
            options={
                'verbose_name': 'respuesta Q&A',
                'verbose_name_plural': 'respuestas Q&A',
                'ordering': ['-is_accepted', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='QnAQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('body', models.TextField(verbose_name='descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
            ],
            options={
                'verbose_name': 'pregunta Q&A',
                'verbose_name_plural': 'preguntas Q&A',
                'ordering': ['-created_at'],
            },
        ),
    ]
