# Generated by Django 5.1.15 on 2026-02-16 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_initial'),
        ('qna', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='qnaanswer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qna_answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qnaquestion',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.lesson'),
        ),
        migrations.AddField(
            model_name='qnaquestion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qna_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qnaanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='qna.qnaquestion'),
        ),
    ]
