[pytest]
DJANGO_SETTINGS_MODULE = config.settings
python_files = test_*.py
testpaths = apps
# --reuse-db acelera las corridas repetidas; se cae la primera vez o con --create-db
addopts = --reuse-db -q
