# Generated by Django 5.1.15 on 2026-02-16 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True, verbose_name='slug')),
                ('content', models.TextField(verbose_name='contenido')),
                ('excerpt', models.TextField(blank=True, default='', verbose_name='extracto')),
                ('cover_image', models.URLField(blank=True, default='', verbose_name='imagen de portada')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado')], default='draft', max_length=20, verbose_name='estado')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de publicación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
            ],
            options={
                'verbose_name': 'artículo del blog',
                'verbose_name_plural': 'artículos del blog',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
