# Generated by Django 5.2.3 on 2026-02-22 17:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_security_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('expires_at', models.DateTimeField(verbose_name='expira en')),
                ('used', models.BooleanField(default=False, verbose_name='usado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'token de recuperación',
                'verbose_name_plural': 'tokens de recuperación',
                'ordering': ['-created_at'],
            },
        ),
    ]
