# Generated by Django 5.1.15 on 2026-03-04 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_password_reset_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='ciudad'),
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='país'),
        ),
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='profile',
            name='has_completed_survey',
            field=models.BooleanField(default=False, verbose_name='ha completado encuesta de intereses'),
        ),
        migrations.AddField(
            model_name='profile',
            name='occupation_type',
            field=models.CharField(blank=True, choices=[('student', 'Estudiante'), ('worker', 'Trabajador'), ('other', 'Otro')], default='', max_length=20, verbose_name='tipo de ocupación'),
        ),
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='estado/provincia'),
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation_type', models.CharField(choices=[('student', 'Estudiante'), ('worker', 'Trabajador'), ('other', 'Otro')], max_length=20, verbose_name='tipo de ocupación')),
                ('interests', models.JSONField(default=list, help_text='Lista de slugs de categorías de interés.', verbose_name='intereses')),
                ('other_interests', models.TextField(blank=True, default='', verbose_name='otros intereses')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='completado en')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='survey_response', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'encuesta de intereses',
                'verbose_name_plural': 'encuestas de intereses',
            },
        ),
    ]
