# Generated by Django 5.2.3 on 2026-03-23 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_add_is_super_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Stripe Customer ID'),
        ),
    ]
