# Generated by Django 5.1.15 on 2026-03-27 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_stripe_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='departamento'),
        ),
        migrations.AddField(
            model_name='profile',
            name='emergency_contact_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='nombre de contacto de emergencia'),
        ),
        migrations.AddField(
            model_name='profile',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='teléfono de contacto de emergencia'),
        ),
        migrations.AddField(
            model_name='profile',
            name='employee_id',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='número de empleado'),
        ),
        migrations.AddField(
            model_name='profile',
            name='hire_date',
            field=models.DateField(blank=True, null=True, verbose_name='fecha de ingreso'),
        ),
        migrations.AddField(
            model_name='profile',
            name='position',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='puesto'),
        ),
    ]
