# Generated by Django 5.1.15 on 2026-09-07 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_avatar_urlfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroDeAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='correo del actor')),
                ('accion', models.CharField(choices=[('crear', 'Crear'), ('actualizar', 'Actualizar'), ('borrar', 'Borrar')], max_length=20, verbose_name='accion')),
                ('recurso', models.CharField(help_text='Ruta del endpoint, sin el id: /api/courses/', max_length=255, verbose_name='recurso')),
                ('recurso_id', models.CharField(blank=True, default='', max_length=64, verbose_name='id del recurso')),
                ('metodo', models.CharField(max_length=10, verbose_name='metodo HTTP')),
                ('ruta', models.CharField(max_length=500, verbose_name='ruta completa')),
                ('codigo_respuesta', models.PositiveSmallIntegerField(verbose_name='codigo de respuesta')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('creado', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='fecha')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_auditadas', to=settings.AUTH_USER_MODEL, verbose_name='actor')),
            ],
            options={
                'verbose_name': 'registro de auditoria',
                'verbose_name_plural': 'registros de auditoria',
                'ordering': ['-creado'],
                'indexes': [models.Index(fields=['actor', '-creado'], name='audit_actor_fecha_idx'), models.Index(fields=['recurso', 'recurso_id', '-creado'], name='audit_recurso_idx')],
            },
        ),
    ]
