# Generated by Django 5.1.15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0003_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonprogress',
            name='video_position_seconds',
            field=models.PositiveIntegerField(
                blank=True,
                help_text='Última posición de reproducción para reanudar.',
                null=True,
                verbose_name='posición del video (segundos)',
            ),
        ),
    ]
