# Generated by Django 5.2.3 on 2026-03-06 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0005_useractivity'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='useractivity',
            new_name='progress_us_user_id_c51269_idx',
            old_name='progress_use_user_id_0b0b0d_idx',
        ),
        migrations.RenameIndex(
            model_name='useractivity',
            new_name='progress_us_action_455164_idx',
            old_name='progress_use_action_1a2b3c_idx',
        ),
    ]
