# Generated by Django 5.2.3 on 2026-03-23 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0006_rename_progress_use_user_id_0b0b0d_idx_progress_us_user_id_c51269_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_event_id', models.CharField(max_length=255, unique=True, verbose_name='Stripe Event ID')),
                ('event_type', models.CharField(max_length=100, verbose_name='tipo de evento')),
                ('payload', models.JSONField(default=dict, verbose_name='payload')),
                ('processed', models.BooleanField(default=False, verbose_name='procesado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='recibido')),
            ],
            options={
                'verbose_name': 'evento webhook Stripe',
                'verbose_name_plural': 'eventos webhook Stripe',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-created_at'], 'verbose_name': 'compra', 'verbose_name_plural': 'compras'},
        ),
        migrations.AddField(
            model_name='purchase',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha de pago completado'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='fecha de creación'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='currency',
            field=models.CharField(default='mxn', max_length=3, verbose_name='moneda'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='metadata'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='receipt_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='URL de recibo'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='monto reembolsado'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='refund_reason',
            field=models.TextField(blank=True, default='', verbose_name='razón del reembolso'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='refund_status',
            field=models.CharField(choices=[('none', 'Sin reembolso'), ('partial', 'Parcial'), ('full', 'Total')], default='none', max_length=20, verbose_name='estado de reembolso'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='stripe_charge_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Stripe Charge ID'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Stripe PaymentIntent ID'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha de pago'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completado'), ('failed', 'Fallido'), ('refunded', 'Reembolsado')], default='pending', max_length=20, verbose_name='estado'),
        ),
    ]
