# Generated by Django 5.2.3 on 2026-03-24 04:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_course_material'),
        ('progress', '0007_stripewebhookevent_alter_purchase_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonprogress',
            options={'ordering': ['-completed_at'], 'verbose_name': 'progreso de lección', 'verbose_name_plural': 'progresos de lecciones'},
        ),
        migrations.AddField(
            model_name='purchase',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='monto de descuento'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='original_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='monto original'),
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='código')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='descripción')),
                ('discount_type', models.CharField(choices=[('percentage', 'Porcentaje'), ('fixed', 'Monto fijo')], default='percentage', max_length=20, verbose_name='tipo de descuento')),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Porcentaje (ej: 20) o monto fijo en MXN.', max_digits=10, verbose_name='valor del descuento')),
                ('max_uses', models.PositiveIntegerField(default=0, help_text='0 = ilimitado.', verbose_name='usos máximos')),
                ('current_uses', models.PositiveIntegerField(default=0, verbose_name='usos actuales')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='válido desde')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='válido hasta')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('applicable_courses', models.ManyToManyField(blank=True, help_text='Si está vacío, aplica a todos los cursos.', to='courses.course', verbose_name='cursos aplicables')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupons_created', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
            ],
            options={
                'verbose_name': 'cupón',
                'verbose_name_plural': 'cupones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='purchase',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='progress.coupon', verbose_name='cupón aplicado'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='número de factura')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='emitida en')),
                ('pdf_url', models.URLField(blank=True, verbose_name='URL del PDF')),
                ('purchase', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='progress.purchase', verbose_name='compra')),
            ],
            options={
                'verbose_name': 'factura',
                'verbose_name_plural': 'facturas',
                'ordering': ['-issued_at'],
            },
        ),
    ]
