# Generated by Django 5.1.15 on 2026-03-04 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('description', models.TextField(verbose_name='descripción')),
                ('section_type', models.CharField(choices=[('maily', 'Maily Academia'), ('public', 'Pública'), ('corporate', 'Corporativo')], max_length=20, verbose_name='tipo de sección')),
                ('logo', models.URLField(blank=True, null=True, verbose_name='logo')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
                ('require_credentials', models.BooleanField(default=False, verbose_name='requiere credenciales especiales')),
                ('allow_public_preview', models.BooleanField(default=False, verbose_name='permitir vista previa pública')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
            ],
            options={
                'verbose_name': 'sección',
                'verbose_name_plural': 'secciones',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SectionMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Estudiante'), ('instructor', 'Instructor'), ('admin', 'Administrador')], default='student', max_length=20, verbose_name='rol en la sección')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
                ('granted_at', models.DateTimeField(auto_now_add=True, verbose_name='otorgada en')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expira en')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_section_memberships', to=settings.AUTH_USER_MODEL, verbose_name='otorgado por')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='sections.section', verbose_name='sección')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_memberships', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'membresía de sección',
                'verbose_name_plural': 'membresías de sección',
                'unique_together': {('user', 'section')},
            },
        ),
    ]
