# Generated by Django 5.2.3 on 2026-03-06 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0002_promovideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promovideo',
            name='embed_url',
            field=models.URLField(max_length=500, verbose_name='URL del embed (YouTube, Vimeo, etc.)'),
        ),
    ]
