# Generated by Django 5.1.15 on 2026-03-27 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BenefitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('icon', models.CharField(blank=True, default='Gift', help_text='Nombre del ícono Lucide', max_length=50, verbose_name='ícono')),
                ('color', models.CharField(default='#e6c364', help_text='Color hexadecimal', max_length=20, verbose_name='color')),
                ('benefit_mode', models.CharField(choices=[('appointment', 'Cita agendada'), ('request', 'Solicitud sin horario')], max_length=20, verbose_name='modo de beneficio')),
                ('requires_approval', models.BooleanField(default=False, verbose_name='requiere aprobación')),
                ('max_per_employee', models.PositiveIntegerField(default=0, help_text='0 = ilimitado', verbose_name='máximo por empleado')),
                ('limit_period', models.CharField(choices=[('monthly', 'Mensual'), ('yearly', 'Anual'), ('total', 'Total')], default='monthly', max_length=20, verbose_name='período de límite')),
                ('slot_duration_minutes', models.PositiveIntegerField(default=60, help_text='Solo aplica en modo cita agendada', verbose_name='duración del slot (minutos)')),
                ('instructions', models.TextField(blank=True, default='', verbose_name='instrucciones')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='orden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
            ],
            options={
                'verbose_name': 'tipo de beneficio',
                'verbose_name_plural': 'tipos de beneficio',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BenefitRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('delivered', 'Entregado')], default='pending', max_length=20, verbose_name='estado')),
                ('notes', models.TextField(blank=True, default='', verbose_name='notas del empleado')),
                ('admin_notes', models.TextField(blank=True, default='', verbose_name='respuesta del administrador')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de revisión')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL, verbose_name='revisado por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefit_requests', to=settings.AUTH_USER_MODEL, verbose_name='empleado')),
                ('benefit_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='corporate.benefittype', verbose_name='tipo de beneficio')),
            ],
            options={
                'verbose_name': 'solicitud de beneficio',
                'verbose_name_plural': 'solicitudes de beneficio',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AvailabilityException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='fecha')),
                ('is_blocked', models.BooleanField(default=True, verbose_name='bloqueado')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='hora de inicio')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='hora de fin')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='motivo')),
                ('benefit_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='corporate.benefittype', verbose_name='tipo de beneficio')),
            ],
            options={
                'verbose_name': 'excepción de disponibilidad',
                'verbose_name_plural': 'excepciones de disponibilidad',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='AvailabilitySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='día de la semana')),
                ('start_time', models.TimeField(verbose_name='hora de inicio')),
                ('end_time', models.TimeField(verbose_name='hora de fin')),
                ('max_concurrent_slots', models.PositiveIntegerField(default=1, verbose_name='slots concurrentes máximos')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('benefit_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='corporate.benefittype', verbose_name='tipo de beneficio')),
            ],
            options={
                'verbose_name': 'horario de disponibilidad',
                'verbose_name_plural': 'horarios de disponibilidad',
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('benefit_type', 'day_of_week', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('message', models.TextField(verbose_name='mensaje')),
                ('notification_type', models.CharField(max_length=50, verbose_name='tipo de notificación')),
                ('related_object_type', models.CharField(blank=True, max_length=50, verbose_name='tipo de objeto relacionado')),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID del objeto relacionado')),
                ('is_read', models.BooleanField(default=False, verbose_name='leída')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corporate_notifications', to=settings.AUTH_USER_MODEL, verbose_name='empleado')),
            ],
            options={
                'verbose_name': 'notificación corporativa',
                'verbose_name_plural': 'notificaciones corporativas',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='corporate_n_user_id_a769e9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='fecha')),
                ('start_time', models.TimeField(verbose_name='hora de inicio')),
                ('end_time', models.TimeField(verbose_name='hora de fin')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('cancelled', 'Cancelada'), ('completed', 'Completada'), ('no_show', 'No se presentó')], default='pending', max_length=20, verbose_name='estado')),
                ('notes', models.TextField(blank=True, default='', verbose_name='notas del empleado')),
                ('admin_notes', models.TextField(blank=True, default='', verbose_name='notas del administrador')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de cancelación')),
                ('cancellation_reason', models.TextField(blank=True, default='', verbose_name='motivo de cancelación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('benefit_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='corporate.benefittype', verbose_name='tipo de beneficio')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_reservations', to=settings.AUTH_USER_MODEL, verbose_name='cancelado por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='empleado')),
            ],
            options={
                'verbose_name': 'reservación',
                'verbose_name_plural': 'reservaciones',
                'ordering': ['-date', '-start_time'],
                'indexes': [models.Index(fields=['benefit_type', 'date', 'status'], name='corp_res_ben_date_status_idx')],
                'unique_together': {('benefit_type', 'date', 'start_time', 'user')},
            },
        ),
    ]
