# Generated by Django 5.1.15 on 2026-09-21 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0004_diploma_congelado'),
        ('sections', '0003_alter_promovideo_embed_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaDeDiploma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='nombre')),
                ('documento', models.JSONField(default=dict, verbose_name='documento')),
                ('alcance', models.CharField(choices=[('global', 'De la plataforma'), ('academia', 'De una academia'), ('instructor', 'De un maestro')], default='instructor', max_length=20, verbose_name='alcance')),
                ('es_semilla', models.BooleanField(default=False, help_text='La que se copia al crear una plantilla nueva. Solo puede haber una.', verbose_name='es la semilla')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('owner', models.ForeignKey(blank=True, help_text='Obligatorio si el alcance es "instructor".', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plantillas_de_diploma', to=settings.AUTH_USER_MODEL, verbose_name='dueño')),
                ('section', models.ForeignKey(blank=True, help_text='Obligatoria si el alcance es "academia".', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plantillas_de_diploma', to='sections.section', verbose_name='academia')),
            ],
            options={
                'verbose_name': 'plantilla de diploma',
                'verbose_name_plural': 'plantillas de diploma',
                'ordering': ['nombre'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('es_semilla', True)), fields=('es_semilla',), name='una_sola_plantilla_semilla')],
            },
        ),
    ]
