# Generated by Django 5.1.15 on 2026-09-21 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0005_plantilla_de_diploma'),
        ('sections', '0003_alter_promovideo_embed_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecursoDeDiploma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('marco', 'Marco de fondo'), ('logo', 'Logotipo'), ('sello', 'Sello')], max_length=20, verbose_name='tipo')),
                ('nombre', models.CharField(max_length=120, verbose_name='nombre')),
                ('cloudinary_public_id', models.CharField(max_length=255, verbose_name='id en Cloudinary')),
                ('ancho_px', models.PositiveIntegerField(default=0, verbose_name='ancho en píxeles')),
                ('alto_px', models.PositiveIntegerField(default=0, verbose_name='alto en píxeles')),
                ('alcance', models.CharField(choices=[('global', 'De la plataforma'), ('academia', 'De una academia'), ('instructor', 'De un maestro')], default='instructor', max_length=20, verbose_name='alcance')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recursos_de_diploma', to=settings.AUTH_USER_MODEL, verbose_name='dueño')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recursos_de_diploma', to='sections.section', verbose_name='academia')),
            ],
            options={
                'verbose_name': 'recurso de diploma',
                'verbose_name_plural': 'recursos de diploma',
                'ordering': ['tipo', 'nombre'],
            },
        ),
    ]
