# Generated by Django 5.1.15 on 2026-02-16 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('passing_score', models.PositiveIntegerField(default=70, verbose_name='puntaje para aprobar (%)')),
                ('module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='courses.module')),
            ],
            options={
                'verbose_name': 'quiz',
                'verbose_name_plural': 'quizzes',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='pregunta')),
                ('options', models.JSONField(help_text='Lista de opciones como array JSON', verbose_name='opciones')),
                ('correct_answer', models.PositiveIntegerField(help_text='Índice base-0 de la opción correcta', verbose_name='índice de respuesta correcta')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='orden')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizzes.quiz')),
            ],
            options={
                'verbose_name': 'pregunta',
                'verbose_name_plural': 'preguntas',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(help_text='Objeto {question_id: selected_index}', verbose_name='respuestas')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='puntaje (%)')),
                ('passed', models.BooleanField(default=False, verbose_name='aprobado')),
                ('attempted_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de intento')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quizzes.quiz')),
            ],
            options={
                'verbose_name': 'intento de quiz',
                'verbose_name_plural': 'intentos de quiz',
                'ordering': ['-attempted_at'],
            },
        ),
    ]
