# Generated by Django 5.2.3 on 2026-03-06 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_question_question_type_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Opción múltiple'), ('true_false', 'Verdadero y falso'), ('word_search', 'Sopa de letras'), ('matching', 'Relacionar palabras'), ('word_order', 'Ordenar palabras'), ('crossword', 'Crucigrama'), ('fill_blank', 'Llenar espacios')], default='multiple_choice', max_length=20, verbose_name='tipo de pregunta'),
        ),
    ]
