# Generated by Django 5.2.3 on 2026-03-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_alter_question_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='max_attempts',
            field=models.PositiveIntegerField(default=0, help_text='0 = intentos ilimitados.', verbose_name='máximo de intentos'),
        ),
    ]
