# Generated by Django 5.1.15 on 2026-03-24 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_add_quiz_max_attempts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finalevaluation',
            options={'ordering': ['course'], 'verbose_name': 'evaluación final', 'verbose_name_plural': 'evaluaciones finales'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['module'], 'verbose_name': 'quiz', 'verbose_name_plural': 'quizzes'},
        ),
    ]
