# Generated by Django 5.1.15 on 2026-02-16 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('description', models.TextField(verbose_name='descripción')),
                ('thumbnail', models.URLField(blank=True, default='', verbose_name='imagen miniatura')),
                ('level', models.CharField(choices=[('beginner', 'Principiante'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzado')], default='beginner', max_length=20, verbose_name='nivel')),
                ('duration', models.CharField(blank=True, default='', max_length=50, verbose_name='duración estimada')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado'), ('archived', 'Archivado')], default='draft', max_length=20, verbose_name='estado')),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='calificación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
            ],
            options={
                'verbose_name': 'curso',
                'verbose_name_plural': 'cursos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('description', models.TextField(blank=True, default='', verbose_name='descripción')),
                ('video_url', models.URLField(help_text='URL del video (YouTube embed por ahora)', verbose_name='URL del video')),
                ('video_provider', models.CharField(choices=[('youtube', 'YouTube'), ('bunny', 'Bunny.net'), ('cloudflare', 'Cloudflare Stream'), ('mux', 'Mux'), ('s3', 'AWS S3')], default='youtube', max_length=20, verbose_name='proveedor de video')),
                ('duration', models.CharField(blank=True, default='', max_length=20, verbose_name='duración')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='orden')),
            ],
            options={
                'verbose_name': 'lección',
                'verbose_name_plural': 'lecciones',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('description', models.TextField(blank=True, default='', verbose_name='descripción')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='orden')),
            ],
            options={
                'verbose_name': 'módulo',
                'verbose_name_plural': 'módulos',
                'ordering': ['order'],
            },
        ),
    ]
