# Generated by Django 5.1.15 on 2026-02-18 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, default='', help_text='URL del video (YouTube embed por ahora)', verbose_name='URL del video'),
        ),
    ]
