# Generated by Django 5.1.15 on 2026-02-18 02:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_lesson_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='precio'),
        ),
    ]
