# Generated by Django 5.1.15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='require_sequential_progress',
            field=models.BooleanField(
                default=False,
                help_text='Si está activo, el alumno debe completar cada lección para desbloquear la siguiente.',
                verbose_name='requerir lecciones en orden',
            ),
        ),
    ]
