# Generated by Django 5.1.15 on 2026-03-04 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_add_final_evaluation_config'),
        ('sections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='section',
            field=models.ForeignKey(blank=True, help_text='Sección a la que pertenece el curso (Maily, Longevity 360, Corporativo).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='sections.section', verbose_name='sección'),
        ),
    ]
