# Generated by Django 5.1.15 on 2026-09-21 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0006_recurso_de_diploma'),
        ('courses', '0010_material_en_cloudinary'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='plantilla_de_diploma',
            field=models.ForeignKey(blank=True, help_text='Diseño del diploma de este curso. Vacío = el de la plataforma.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos', to='certificates.plantilladediploma', verbose_name='plantilla de diploma'),
        ),
    ]
