# Generated by Django 5.1.15 on 2026-09-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_plantilla_de_diploma_en_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='es_gratuita',
            field=models.BooleanField(default=False, help_text='Si se marca, cualquiera con una cuenta puede verla aunque no tenga acceso al curso. Solo surte efecto en cursos publicados de academias con vitrina publica.', verbose_name='abierta como muestra'),
        ),
    ]
